# Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: 👤 User story
description: Describe desired capability from User, Developer or other role's perspective
title: As a developer I would like to ...
labels: [enhancement]
projects:
  - turboBasic/3
body:
  - type: textarea
    attributes:
      label: User story content
      description: A concise description of the capability you would like to have
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about your proposal!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
