# Documentation: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

name: 🐞 Bug
description: Create a report to help us improve
title: "bug: ..."
labels: [bug]
projects:
  - turboBasic/3
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. In this environment...
        2. With this config...
        3. Go to ... / Run '...' / Click ... / Scroll down to ...
        4. See error ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        Describe details of your environment (hardware, OS, SDKs, build tools, browser etc.)

        Tip: You can also specify versions of **Android SDK**, **Java**, **CMake**, **LLVM**, **Python** if applicable
      value: |
        - **Device**: (if bug is observed on a smartphone, specify its model name)
        - **OS**: Ubuntu 24.04, macOS Sonoma 14.6, iOS 17.6, ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
